/**
 * These hosts were reviewed as workbook guidance in the catalog source review.
 * Membership here does not make a URL acceptable as direct evidence. Direct
 * evidence seeds are derived exclusively from the curated runtime registry.
 */
export const REVIEWED_CATALOG_GUIDANCE_DOMAINS = [
  "accaglobal.com",
  "adaptation-undp.org",
  "adb.org",
  "adnoc.ae",
  "adx.ae",
  "aesg.com",
  "agsi.org",
  "aiib.org",
  "api.mf.uz",
  "assets.kpmg.com",
  "carboncapturemena.com",
  "carececo.org",
  "careforsustainability.com",
  "cdn.cdp.net",
  "cdp.net",
  "centralbank.ae",
  "cis-legislation.com",
  "climate-laws.org",
  "climate.ec.europa.eu",
  "climateactiontracker.org",
  "climatebonds.net",
  "climatepromise.undp.org",
  "cma.gov.sa",
  "commission.europa.eu",
  "crrem.org",
  "data.consilium.europa.eu",
  "documents1.worldbank.org",
  "doe.gov.ae",
  "ebrd.com",
  "ecovadis.com",
  "emiratesgbc.org",
  "emiratesislamic.ae",
  "equator-principles.com",
  "eur-lex.europa.eu",
  "fao.org",
  "faolex.fao.org",
  "files.sciencebasedtargets.org",
  "fsb.org",
  "gfanzero.com",
  "gfc.aifc.kz",
  "gggi.org",
  "gh2.org",
  "ghgprotocol.org",
  "globalbattery.org",
  "globaltailingsreview.org",
  "gov.uz",
  "greenfinanceplatform.org",
  "greenpolicyplatform.org",
  "gresb.com",
  "hgeo.energy.gov",
  "iata.org",
  "icapcarbonaction.com",
  "icmagroup.org",
  "icmm.com",
  "iea.blob.core.windows.net",
  "iea.org",
  "ifc.org",
  "ifrs.org",
  "imo.org",
  "invest.gov.uz",
  "ipcc.ch",
  "ipieca.org",
  "irena.org",
  "jll.com",
  "kayrouzandassociates.com",
  "lseg.com",
  "mckinsey.com",
  "meira.me",
  "moenergy.gov.sa",
  "moet.gov.ae",
  "msci.com",
  "ngfs.net",
  "oecd.org",
  "oecdecoscope.blog",
  "ogci.com",
  "ogmpartnership.org",
  "openknowledge.worldbank.org",
  "policy.asiapacificenergy.org",
  "pwc.com",
  "responsiblemineralsinitiative.org",
  "rulebook.centralbank.ae",
  "saudienergyconsulting.com",
  "saudipedia.com",
  "sgi.gov.sa",
  "sgs.com",
  "spa.gov.sa",
  "sseinitiative.org",
  "sustainalytics.com",
  "swissre.com",
  "switch-asia.eu",
  "taxation-customs.ec.europa.eu",
  "thaimiddleeast.com",
  "theenvironmentconsultant.com",
  "tnfd.global",
  "u.ae",
  "uaelegislation.gov.ae",
  "un.org",
  "unctad.org",
  "undp.org",
  "unece.org",
  "unepfi.org",
  "unfccc.int",
  "unpri.my.salesforce.com",
  "unpri.org",
  "usgbc.org",
  "uzembassy.kz",
  "vision2030.gov.sa",
  "wecoop.eu",
  "worldbank.org",
  "wri.org",
  "www3.weforum.org",
  "zerotracker.net",
] as const;

export function normalizeCatalogHostname(hostname: string): string {
  return hostname.trim().toLowerCase().replace(/^www\./, "");
}

export function domainMatchesCatalogPolicy(
  hostname: string,
  policyDomain: string,
): boolean {
  const normalizedHost = normalizeCatalogHostname(hostname);
  const normalizedPolicy = normalizeCatalogHostname(policyDomain);
  return (
    normalizedHost === normalizedPolicy ||
    normalizedHost.endsWith(`.${normalizedPolicy}`)
  );
}
